site_name: LEMMA Documentation
repo_name: seelabfhdo/lemma
repo_url: https://github.com/seelabfhdo/lemma
edit_uri: https://github.com/seelabfhdo/lemma-docs/edit/main/docs/
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
plugins:
  - search
  - git-authors
  - git-revision-date
  - macros:
      module_name: additional_macros
      include_yaml:
        - docs/developer-guide/intermediate-model-specifications/intermediate-domain-model-specification/specification.yaml
        - docs/developer-guide/intermediate-model-specifications/intermediate-operation-model-specification/specification.yaml
        - docs/developer-guide/intermediate-model-specifications/intermediate-service-model-specification/specification.yaml
markdown_extensions:
  - admonition
  - attr_list
  - extra
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['docs']
      check_paths: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
nav:
  - 'Welcome': 'index.md'
  - 'Context and Motivation': 'context-motivation/index.md'
  - 'Feature Overview': 'feature-overview/index.md'
  - 'Getting Started':
    - 'Installation': 'getting-started/index.md'
    - 'Tour': 'getting-started/tour/index.md'
  - 'User Guide':
    - 'Introduction': 'user-guide/index.md'
    - 'Domain Data Modeling Language': 'user-guide/domain-data-modeling-language/index.md'
    - 'Technology Modeling Language': 'user-guide/technology-modeling-language/index.md'
    - 'Service Modeling Language': 'user-guide/service-modeling-language/index.md'
    - 'Service Technology Mapping Modeling Language': 'user-guide/service-technology-mapping-modeling-language/index.md'
    - 'Operation Modeling Language': 'user-guide/operation-modeling-language/index.md'
#    - 'Model Processing':
#      - 'Introduction': 'user-guide/model-processing/index.md'
#      - 'Static Analysis': 'user-guide/model-processing/static-analysis/index.md'
  - 'Developer Guide':
    - 'Introduction': 'developer-guide/index.md'
    - 'Coding Style': 'developer-guide/coding-style/index.md'
    - 'Intermediate Model Specifications':
        - 'Introduction': 'developer-guide/intermediate-model-specifications/index.md'
        - 'Obtaining Intermediate Models': 'developer-guide/intermediate-model-specifications/obtaining-intermediate-models/index.md'
        - 'Intermediate Domain Model Specification': 'developer-guide/intermediate-model-specifications/intermediate-domain-model-specification/index.md'
        - 'Intermediate Service Model Specification': 'developer-guide/intermediate-model-specifications/intermediate-service-model-specification/index.md'
        - 'Intermediate Operation Model Specification': 'developer-guide/intermediate-model-specifications/intermediate-operation-model-specification/index.md'
    - 'Model Processing Framework': 'developer-guide/model-processing-framework/index.md'
    - "Integrating New Modules With LEMMA's Continuous Integration Pipeline": 'developer-guide/continuous-integration/index.md'
    - 'Extending the Java Base Generator': 'developer-guide/java-base-generator-extension/index.md'
    - 'Static Analysis Library': 'developer-guide/static-analysis-library/index.md'
  - 'Research': 'research/index.md'
  - 'Contact': 'contact/index.md'
extra:
  api_definition_url: https://en.wikipedia.org/wiki/API
  atl_url: https://www.eclipse.org/atl
  bounded_context_url: https://www.martinfowler.com/bliki/BoundedContext.html
  cite_thesis: "Rademacher, Florian: <emph>A Language Ecosystem for Modeling
  Microservice Architecture</emph>. University of Kassel, Department of
  Electrical Engineering and Computer Science, PhD Thesis, October 2022.
  <a href=\"https://kobra.uni-kassel.de/handle/123456789/14176\">
  https://kobra.uni-kassel.de/handle/123456789/14176
  </a>. – 867 p."
  coding_style_column_width: 100
  coding_style_language: American English
  coding_style_tab_size: 4
  container_def_url: https://www.docker.com/resources/what-container
  current_eclipse_release: 2022-09
  cqrs_pattern_def_url: https://microservices.io/patterns/data/cqrs.html
  ddd_aggregate_def_url: https://www.martinfowler.com/bliki/DDD_Aggregate.html
  ddd_def_url: https://en.wikipedia.org/wiki/Domain-driven_design
  ddd_entity_def_url: https://www.martinfowler.com/bliki/EvansClassification.html
  ddd_tactical_patterns_url: https://www.thedomaindrivendesign.io/what-is-tactical-design/
  ddd_value_object_def_url: https://www.martinfowler.com/bliki/ValueObject.html
  default_indent_level1: 2%
  default_indent_level2: 4%
  devops_culture_url: https://www.martinfowler.com/bliki/DevOpsCulture.html
  docker_url: https://www.docker.com
  docker_installation_url: https://docs.docker.com/get-docker
  dto_definition_url: https://www.martinfowler.com/eaaCatalog/dataTransferObject.html
  employed_gradle_releases: 5.2.1, 6.1.1, 6.3, 6.8, 7.1.1
  gradle_url: https://gradle.org
  info_email: florian.rademacher@fh-dortmund.de
  ioc_def_url: https://en.wikipedia.org/wiki/Inversion_of_control
  kr_coding_style_url: https://en.wikipedia.org/wiki/Indentation_style#K&R_style
  java_primitive_types_url: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html
  lemma_build_server_url: https://build.seelab.fh-dortmund.de
  lemma_build_job_url: https://build.seelab.fh-dortmund.de/job/SeelabFhdo/job/lemma
  lemma_github_url: https://github.com/SeelabFhdo/lemma
  lemma_main_branch_name: main
  lemma_repository_server_url: https://repository.seelab.fh-dortmund.de/
  lemma_repository_artifacts_url: https://repository.seelab.fh-dortmund.de/#browse/search/maven
  lemma_repository_docker_images_url: https://repository.seelab.fh-dortmund.de/#browse/search/docker
  lemma_tour_cqrs_model_repository_url: https://github.com/SeelabFhdo/lemma/blob/main/examples/charging-station-management/models/technology/Cqrs.technology
  lemma_tour_domain_model_file: ChargingStationManagement.data
  lemma_tour_java_technology_model_url: https://github.com/SeelabFhdo/lemma/blob/main/examples/charging-station-management/models/technology/Java.technology
  lemma_tour_models_project_name: charging-station-management
  lemma_tour_model_repository_url: https://www.github.com/SeelabFhdo/lemma/tree/main/examples/charging-station-management/models
  lemma_tour_model_repository_query_side_url: https://www.github.com/SeelabFhdo/lemma/tree/main/examples/charging-station-management/models/microservices/query-side
  lemma_tour_service_model_file: ChargingStationManagementCommandSide.services
  lemma_tour_service_name: ChargingStationManagement
  lemma_tour_spring_technology_model_url: https://github.com/SeelabFhdo/lemma/blob/main/examples/charging-station-management/models/technology/Spring.technology
  lemma_updatesite_url: https://microservices.fh-dortmund.de/lemma/
  maven_url: https://maven.apache.org
  maven_build_profiles_url: https://maven.apache.org/guides/introduction/introduction-to-profiles.html
  maven_pom_url: https://maven.apache.org/pom.html
  mde_def_url: https://en.wikipedia.org/wiki/Model-driven_engineering
  minimum_eclipse_release: 2021-03
  minimum_java_release: 11
  minimum_linux_release: Ubuntu 18.04 LTS (Bionic Beaver)
  minimum_linux_release_for_docker: Debian GNU/Linux 10 (buster)
  minimum_maven_release: 3.6.3
  minimum_windows_release: 10
  monolith_def_url: https://en.wikipedia.org/wiki/Monolithic_application
  msa_bc_url: https://www.martinfowler.com/articles/microservices.html#DecentralizedDataManagement
  msa_def_url: https://www.martinfowler.com/articles/microservices.html
  msa_tech_heterogeneity_url: https://www.oreilly.com/library/view/building-microservices/9781491950340/ch01.html
  ntier_def_url: https://en.wikipedia.org/wiki/Multitier_architecture
  openapi_spec_url: https://www.openapis.org
  pep8_url: https://www.python.org/dev/peps/pep-0008
  rest_definition_url: https://en.wikipedia.org/wiki/Representational_state_transfer
  saga_pattern_def_url: https://microservices.io/patterns/data/saga.html
  spring_get_mapping_annotation_url: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/GetMapping.html
  spring_response_status_annotation_url: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/ResponseStatus.html
  spring_url: https://www.spring.io
  tech_hetero_def_url: https://www.oreilly.com/library/view/building-microservices/9781491950340/ch01.html#idm46346970503816
  xcore_url: https://wiki.eclipse.org/Xcore
  xmi_url: https://www.omg.org/spec/XMI/2.5.1/About-XMI
  xtend_url: https://www.eclipse.org/xtend
  xtext_standalone_url: https://www.typefox.io/blog/how-and-why-use-xtext-without-the-ide
